server:
  port: 8080
  servlet:
    contextPath: /telemetry

spring:
  liquibase:
    change-log: classpath:db/db-changelog-master.xml
    enabled: true
    default-schema: telemetry
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://173.17.0.5:5432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
      dialect:
    show-sql: true
    database: postgresql
    open-in-view: true
    initialize: false
    properties:
      hibernate:
        order_by.default_null_ordering: first
        format_sql: true
        user_sql_comments: true
        default_schema: telemetry
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    consumer:
      bootstrap-servers: 173.17.0.6:9092,173.17.0.7:9094,173.17.0.8:9096
      group-id: telemetry-group
      client-id: telemetry-client
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.value.default.type: org.example.dto.TelemetryData
      properties.spring.json.trusted.packages: org.example.dto

app:
  kafka:
    topic:
      telemetries: TELEMETRIES